server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index login.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Вимикаємо логування для статичних файлів, щоб не засмічувати логи
    location ~* \.(css|js|png|jpg|jpeg|gif|ico)$ {
        include /etc/nginx/mime.types;
        access_log off;
        expires max;
    }
}

server {
    listen 443 ssl;
    server_name localhost;


    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    root /var/www/html;
    index login.html;
}
